### ISSUE TITLE
Users Changing Fortunes

### ISSUE THREAD

**Issue by AlbertXDing** [cse110-sp23-group1/Origami-Fortune-Teller#1] opened 2023-05-11 07:11 UTC
The user should have the option to change these by clicking on any box. This will create a new overlaying text box where the user can submit their new fortune.

**Comment by adarsh249** [comment] 2023-05-11 22:26
Issue cse110-sp23-group1/Oragami-Fortune-Teller#2 must be done before doing this issue.

**Comment by phentos** [comment] 2023-05-15 02:01
Why not edit the fortune in-line?

**Comment by phentos** [comment] 2023-05-15 02:07
duplicate of #3

**Closed as completed by phentos** 2023-05-15 02:07 UTC
